name: "JFrog Build"

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          # JFrog platform url (for example: https://acme.jfrog.io)
          JF_URL: ${{ vars.JF_URL }}

          # JFrog Platform access token
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}

          # Basic authentication credentials
          ## JF_USER: ${{ secrets.JF_USER }}
          ## JF_PASSWORD: ${{ secrets.JF_PASSWORD }}

      - name: Run JFrog CLI
        run: |
          # Ping the server
          jf rt ping
          
          # scan
          #jf s "./target/*.jar" 
          
          # Collect environment variables for the build
          jf rt bce
          #mock BUILD section
          jf docker pull infomagnus.jfrog.io/m1-docker-local-ingress/webgoat/webgoat:latest
          docker tag infomagnus.jfrog.io/m1-docker-local-ingress/webgoat/webgoat:latest infomagnus.jfrog.io/m1-docker-local-release/webgoat:latest
          #PUSH to STAGING
          jf docker push infomagnus.jfrog.io/m1-docker-local-release/webgoat
          # Collect VCS details from git and add them to the build
          jf rt bag
          # Publish build info
          jf rt bp
          # Build Scan
          jf build-scan
          # TEST
          #RELEASE
