name: "JFrog Build2"
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: JFrog Build 2
        uses: jfrog/setup-jfrog-cli@v4
        env:
          # JFrog platform url (for example: https://acme.jfrog.io)
          JF_URL: ${{ vars.JF_URL }}

          # JFrog Platform access token
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}

          # Basic authentication credentials
          ## JF_USER: ${{ secrets.JF_USER }}
          ## JF_PASSWORD: ${{ secrets.JF_PASSWORD }}

      - name: Run JFrog CLI
        run: |
          # Ping the server
          jf rt ping
          
          # scan
          #jf s "./target/*.jar" 
          
          # Collect environment variables for the build
          jf rt bce
          #jf docker pull trialj4xtng.jfrog.io/m1-local-docker-ingress/webgoat:latest
          #docker ps 
          #echo 'this is '
          #docker tag trialj4xtng.jfrog.io/m1-local-docker-ingress/webgoat:latest trialj4xtng.jfrog.io/m1-local-docker-release/webgoat:latest
          
          #jf docker push trialj4xtng.jfrog.io/m1-local-docker-release/webgoat
          jf mvn-config
          jf mvn compile
          # Collect VCS details from git and add them to the build
          jf rt bag
          # Publish build info
          jf rt bp
          # Build Scan
          *jf build-scan
      
